### ISSUE TITLE
How to start up project?

### ISSUE THREAD

**Issue by s-Hale** [ashutoshkrris/Random-APIs#13]
Nothing in the readme, npm start, npm run... ?

**Comment by ashutoshkrris** [comment]
Hey @s-Hale 
It's there in the README.
You can find a section called Local Setup.
You can use Live Server in VS Code to view the outputs

**Comment by s-Hale** [comment]
Yes, I installed and built. No run? Not used liveserver before.

**Comment by ashutoshkrris** [comment]
If you're VS Code, you can install an extension called Live Server. After it's installed, right click on index.html and Open with Live Server

If you don't have VS Code, directly open the index.html file in your browser, it would work perfectly
