### ISSUE TITLE
Add tailwindcss + a random api

### ISSUE THREAD

**Issue by apoorvcodes** [ashutoshkrris/Random-APIs#7]
### Is your feature request related to a problem? Please describe.
Can I add a random api and also tailwind css

### Describe the solution you'd like
tailwind css is much easier and way faster to style things, it may introduce many devs to the project itself

### Which Program are you part of?

- [x] Hacktoberfest21
- [ ] Any other

**Comment by ashutoshkrris** [comment]
That would be an amazing contribution to the project, @apoorvcodes!
Go on.

**Comment by apoorvcodes** [comment]
sure
